"""init

Revision ID: 21aea49017ec
Revises: 
Create Date: 2026-05-12 14:17:57.045248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21aea49017ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('LACE', 'SATIN', 'CHIFFON', 'VELVET', 'BROCADE', 'SILK', 'OTHER', name='fabriccategory'), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('price_per_meter', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fabrics_external_id'), 'fabrics', ['external_id'], unique=False)
    op.create_table('fitting_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('slot_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_date', 'slot_time', name='uq_slot')
    )
    op.create_index(op.f('ix_fitting_slots_slot_date'), 'fitting_slots', ['slot_date'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('WEDDING', 'EVENING', 'CORSET', name='producttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('look', sa.Enum('CASUAL', 'OFFICE', 'EVENING', 'SUMMER', 'WINTER', 'PARTY', 'BRIDAL', name='look'), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('consent_personal_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('WEDDING', 'EVENING', 'CORSET', name='producttype'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'AWAITING_FITTING', 'IN_PROGRESS', 'READY', 'DELIVERED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=128), nullable=True),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corset_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('bust', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bra_size', sa.String(length=16), nullable=True),
    sa.Column('under_bust', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waist', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('desired_tight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('belly', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hips', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waist_to_under_bust', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('figure_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fittings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'DECLINED', 'DONE', name='fittingstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['fitting_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fittings')
    op.drop_table('corset_measurements')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('products')
    op.drop_index(op.f('ix_fitting_slots_slot_date'), table_name='fitting_slots')
    op.drop_table('fitting_slots')
    op.drop_index(op.f('ix_fabrics_external_id'), table_name='fabrics')
    op.drop_table('fabrics')
    # ### end Alembic commands ###
